[program:h2]
command = java -Djava.rmi.server.hostname=192.168.1.99 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=8880 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dorg.h2.modules.MULTI_THREADED=true -Dh2.cacheSize=262144 -XX:+HeapDumpOnOutOfMemoryError -Xmx256m -cp h2-2.3.232.jar org.h2.tools.Server -webPort 8081 -baseDir /home/servadmin -tcp -web -ifNotExists -tcpAllowOthers
priority=100
directory = /home/username
user = username
startsecs = 0
autostart = true
autorestart = true  
stdout_logfile = /home/username/logs/h2.log  
stderr_logfile = /home/username/logs/h2_err.log

