<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.2</version> 
        <relativePath/> 
    </parent>

    <groupId>com.codeferm</groupId>
    <artifactId>alarmbian</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    
    <name>Alarmbian</name>
    <url>https://github.com/sgjava/alarmbian</url>
    
    <modules>
        <module>image</module>        
        <module>data</module>
        <module>server</module>
        <module>client</module>
    </modules>
    
    <properties>
        <java.version>21</java.version>
        <maven.compiler.release>${java.version}</maven.compiler.release>
        <lombok.version>1.18.38</lombok.version>        
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <site.installationModule>${project.artifactId}</site.installationModule>
        <spring-cloud.version>2023.0.2</spring-cloud.version>
        <opencv>${user.home}/opencv/build/bin/opencv-4130.jar</opencv>
        <opencv.lib>${user.home}/opencv/build/lib</opencv.lib>
        <opencv.version>4.13.0</opencv.version>
    </properties>
    
    <!-- Do 'mvn initialize -Pinstall-opencv' once to install OpenCV jar you compiled -->
    <profiles>
        <profile>
            <id>install-opencv</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-install-plugin</artifactId>
                        <version>3.1.2</version>
                        <executions>
                            <execution>
                                <id>install-opencv</id>
                                <phase>initialize</phase>
                                <goals>
                                    <goal>install-file</goal>
                                </goals>
                                <configuration>
                                    <file>${opencv}</file>
                                    <groupId>org.opencv</groupId>
                                    <artifactId>opencv</artifactId>
                                    <version>${opencv.version}</version>
                                    <packaging>jar</packaging>
                                    <localRepositoryPath>${user.home}/.m2/repository</localRepositoryPath>
                                    <generatePom>true</generatePom>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>             
</project>