# Main
spring.main.banner-mode = off
spring.main.log-startup-info = false
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

# Native Spring Boot boot-strapping property import line.
# 'optional:' allows application context integration tests to pass if run locally.
spring.config.import=optional:file:/etc/alarmbian/server-secrets.properties

# Database
spring.datasource.url = jdbc:h2:tcp://localhost/nio:test
spring.datasource.driverClassName = org.h2.Driver
spring.jpa.database-platform = org.hibernate.dialect.H2Dialect
# Let's create schema manually instead of hibernate using schema.sql
spring.jpa.hibernate.ddl-auto = none
# We run always, but script checks if objects exist first
spring.sql.init.mode = always

# Device
device.name = cam1
# Runtime https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html?is-external=true#parse-java.lang.CharSequence-
device.runtime = P365D
# How often to run file/dir/db cleaner https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html?is-external=true#parse-java.lang.CharSequence-
device.clean.runtime = PT60M
# Age of files to keep in milliseconds (86400000 is one day)
device.clean.age = 604800000

# FFMPEG general
ffmpeg.bin = /usr/local/bin/
ffmpeg.container = mkv
ffmpeg.dir.pattern = MMddyyyy
ffmpeg.file.pattern = HHmmss
ffmpeg.output.path = /home/servadmin/Downloads

# Mainstream is used to record 24/7 and should be max frame size and FPS
mainstream.name = h265+
mainstream.class = com.codeferm.alarmbian.image.FfmpegOut
mainstream.device = rtsp://${camera.mainstream.username}:${camera.mainstream.password}@192.168.1.12:554/H265/ch1/main/av_stream
mainstream.timeout = 10000
mainstream.file.suffix = main
mainstream.input.args = {}
mainstream.output.args = {'-fflags':'nobuffer', '-hide_banner':null, '-loglevel':'warning'}
mainstream.length = 3600000

# Substream is used for detection and should be 640x480 3 or 4 FPS
substream.name = h265
substream.class = com.codeferm.alarmbian.image.VideoIn
substream.device = rtsp://localhost:8554/sub1
substream.timeout = 10000
substream.input.args = {}

# Motion detection
motion.class = com.codeferm.alarmbian.image.Motion
motion.ksize = 8,8
motion.alpha = 0.03
motion.black.threshold = 25.0
motion.max.threshold = 255.0
motion.max.change = 25.0
motion.start.threshold = 1.0
motion.stop.threshold = 0.0
motion.ignore.mask =

# Supported extensions https://docs.opencv.org/master/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56
history.output.path = /home/servadmin/Downloads
history.writer.extension = .jpg

# Deepstack
deepstack.enabled = false
deepstack.url = http://localhost
deepstack.image.extension = .jpg
