# Main
spring.main.banner-mode = off
spring.main.log-startup-info = false

# Let in flight requests complete 
server.shutdown = graceful

# Database
spring.datasource.url = jdbc:h2:tcp://192.168.1.40/nio:test
spring.datasource.driverClassName = org.h2.Driver
spring.datasource.username = sa
spring.datasource.password = sa

# We run always, but script checks if objects exist first
spring.sql.init.mode = always

# Device
device.name = cam1

# Remote from path for recordings
remoteFromPath = /data1

# Remote to path for recordings
remoteToPath = /mnt/data1

# Used for saving video clips
localPath = /home/servadmin/Downloads

# Start before time in seconds
playBefore = 5

# End after time in seconds
playAfter = 5

# Display X max
xMax = 1280

# Display Y max
yMax = 720
