#
# Created by DeTOnator on 07-22-2021 19:54:53.
#
# select * from EVENTS
#
findAll = select DEVICE_NAME, EVENTS_ID, EVENT_DATA, EVENT_TIME, EVENT_TYPE from EVENTS
find = select DEVICE_NAME, EVENTS_ID, EVENT_DATA, EVENT_TIME, EVENT_TYPE from EVENTS where EVENTS_ID = ?
findRange = select DEVICE_NAME, EVENTS_ID, EVENT_DATA, EVENT_TIME, EVENT_TYPE from EVENTS where (EVENTS_ID >= ?) and (EVENTS_ID <= ?)
save = insert into EVENTS (DEVICE_NAME, EVENTS_ID, EVENT_DATA, EVENT_TIME, EVENT_TYPE) values (?, ?, ?, ?, ?)
update = update EVENTS set DEVICE_NAME = ?, EVENTS_ID = ?, EVENT_DATA = ?, EVENT_TIME = ?, EVENT_TYPE = ? where EVENTS_ID = ?
delete = delete from EVENTS where EVENTS_ID = ?
findEvent = select DEVICE_NAME, EVENTS_ID, EVENT_DATA, EVENT_TIME, EVENT_TYPE from EVENTS where DEVICE_NAME = ? and EVENT_TYPE = ? order by EVENTS_ID
findMotionEvents = select DEVICE_NAME, EVENTS_ID, EVENT_DATA, EVENT_TIME, EVENT_TYPE from EVENTS where DEVICE_NAME = ? and EVENT_TYPE in ('MOTION_START', 'MOTION_STOP', 'HISTORY_STOP') order by EVENTS_ID
findBuffers = select DEVICE_NAME, EVENTS_ID, EVENT_DATA, EVENT_TIME, EVENT_TYPE from EVENTS where DEVICE_NAME = ? and EVENT_TYPE = 'RECORD_START' order by EVENTS_ID
findMotionFiles = select DEVICE_NAME, EVENTS_ID, EVENT_DATA, EVENT_TIME, EVENT_TYPE from EVENTS where DEVICE_NAME = ? and EVENT_TYPE in ('MOTION_START', 'MOTION_STOP', 'MOTION_RESET', 'HISTORY_STOP') order by EVENTS_ID
deleteByEventData = delete from EVENTS where EVENT_DATA = ?